import { z } from "zod";
import { configSchema, defaultConfig } from "../config/config";
import { phraseSchema, type Phrase } from "../data/phrase";
// Real chapter-1 batches, generated by `npm run data:export-sample` (Node
// script, talks to Postgres via Prisma). Never import getPhrases.ts/Prisma
// directly here - this file is bundled into the browser Remotion renders
// in, and Prisma's native engine can't run there. Re-run the export script
// after DB content changes to refresh this preview data.
import sampleBatchesJson from "./sample-data.json";

// Props shape shared by every recipe-driven composition (see
// recipe/CompositionFromRecipe.tsx) - moved out of the old per-template
// Reel.tsx (now retired in favor of the recipe renderer, preserved on the
// backup/legacy-composition-renderer branch) since it was never actually
// template-specific: every composition takes the same phrases/config/audio
// shape, only how it's sequenced into scenes differs, which is now a
// CompositionRecipe's job, not this file's.

export const sampleBatches = sampleBatchesJson as Phrase[][];

// A Zod schema (not a plain TS type) so Remotion Studio renders a real form
// for every field in its sidebar - see config.ts for the same reasoning on
// configSchema, which this embeds.
export const reelPropsSchema = z.object({
  phrases: z.array(phraseSchema),
  config: configSchema,
  musicFile: z.string().nullable().describe("Filename under assets/music, picked by renderBatch.ts"),
  musicStartFrame: z.number().describe("Frame offset into musicFile to start playback from"),
  tickFile: z.string().nullable().describe("Filename under assets/sfx for the countdown ambience track"),
  revealSoundFile: z.string().nullable().describe("Filename under assets/sfx for the reveal-moment stinger"),
  introVoiceFile: z.string().nullable().describe('Filename under assets/voice for the intro "guess the meaning" prompt'),
  ttsPhraseFiles: z.array(z.string().nullable()).describe("Per-phrase English TTS filenames under assets/tts"),
  ttsRevealFiles: z.array(z.string().nullable()).describe("Per-phrase Sinhala TTS filenames under assets/tts"),
});

export type ReelProps = z.infer<typeof reelPropsSchema>;

export const reelDefaultProps: ReelProps = {
  phrases: sampleBatches[0],
  config: defaultConfig,
  musicFile: null,
  musicStartFrame: 0,
  tickFile: null,
  revealSoundFile: null,
  introVoiceFile: null,
  ttsPhraseFiles: [],
  ttsRevealFiles: [],
};
