import { Fragment, type ReactNode } from "react";
import { z } from "zod";
import { Html5Audio, staticFile, type CalculateMetadataFunction } from "remotion";
import { TransitionSeries, linearTiming } from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";
import { IntroScene } from "./scenes/IntroScene";
import { PhraseScene } from "./scenes/PhraseScene";
import { CountdownScene } from "./scenes/CountdownScene";
import { RevealScene } from "./scenes/RevealScene";
import { OutroScene } from "./scenes/OutroScene";
import { buildTimeline, totalDuration } from "./timings";
import { configSchema, defaultConfig } from "../config/config";
import { ThemeProvider } from "../theme/ThemeContext";
import { phraseSchema, type Phrase } from "../data/phrase";
// Real chapter-1 batches, generated by `npm run data:export-sample` (Node
// script, talks to Postgres via Prisma). Never import getPhrases.ts/Prisma
// directly here - this file is bundled into the browser Remotion renders
// in, and Prisma's native engine can't run there. Re-run the export script
// after DB content changes to refresh this preview data.
import sampleBatchesJson from "./sample-data.json";

export const sampleBatches = sampleBatchesJson as Phrase[][];

// A Zod schema (not a plain TS type) so Remotion Studio renders a real form
// for every field in its sidebar - see config.ts for the same reasoning on
// configSchema, which this embeds.
export const reelPropsSchema = z.object({
  phrases: z.array(phraseSchema),
  config: configSchema,
  musicFile: z.string().nullable().describe("Filename under assets/music, picked by renderBatch.ts"),
  musicStartFrame: z.number().describe("Frame offset into musicFile to start playback from"),
  tickFile: z.string().nullable().describe("Filename under assets/sfx for the countdown ambience track"),
  revealSoundFile: z.string().nullable().describe("Filename under assets/sfx for the reveal-moment stinger"),
  introVoiceFile: z.string().nullable().describe('Filename under assets/voice for the intro "guess the meaning" prompt'),
  ttsPhraseFiles: z.array(z.string().nullable()).describe("Per-phrase English TTS filenames under assets/tts"),
  ttsRevealFiles: z.array(z.string().nullable()).describe("Per-phrase Sinhala TTS filenames under assets/tts"),
});

export type ReelProps = z.infer<typeof reelPropsSchema>;

export const reelDefaultProps: ReelProps = {
  phrases: sampleBatches[0],
  config: defaultConfig,
  musicFile: null,
  musicStartFrame: 0,
  tickFile: null,
  revealSoundFile: null,
  introVoiceFile: null,
  ttsPhraseFiles: [],
  ttsRevealFiles: [],
};

export const calculateReelMetadata: CalculateMetadataFunction<ReelProps> = ({ props }) => {
  const timeline = buildTimeline(props.phrases.length, props.config);
  const transitionFrames = Math.round(props.config.transitionSeconds * props.config.fps);
  return {
    durationInFrames: totalDuration(timeline, transitionFrames),
    fps: props.config.fps,
    width: props.config.width,
    height: props.config.height,
  };
};

export function Reel({
  phrases,
  config,
  musicFile,
  musicStartFrame,
  tickFile,
  revealSoundFile,
  introVoiceFile,
  ttsPhraseFiles,
  ttsRevealFiles,
}: ReelProps) {
  const timeline = buildTimeline(phrases.length, config);
  const transitionFrames = Math.round(config.transitionSeconds * config.fps);
  // Only the reveal-to-outro cut gets a crossfade (per Dan's feedback that
  // it "suddenly appears") - every other cut (phrase->countdown->reveal)
  // stays an instant cut, which reads better for the quiz-beat pacing.
  const lastRevealIndex = timeline.map((item) => item.type).lastIndexOf("reveal");

  return (
    <ThemeProvider theme={config.theme}>
      {musicFile && (
        <Html5Audio src={staticFile(`music/${musicFile}`)} loop trimBefore={musicStartFrame} volume={config.musicVolume} />
      )}
      <TransitionSeries>
        {timeline.map((item, i) => {
          let content: ReactNode;
          if (item.type === "intro") {
            content = <IntroScene text={config.introText} voiceFile={introVoiceFile} voiceVolume={config.introVoiceVolume} />;
          } else if (item.type === "phrase") {
            content = (
              <PhraseScene
                phrase={phrases[item.phraseIndex]}
                index={item.phraseIndex}
                total={phrases.length}
                ttsFile={ttsPhraseFiles[item.phraseIndex] ?? null}
                ttsVolume={config.phraseVoiceVolume}
              />
            );
          } else if (item.type === "countdown") {
            content = (
              <CountdownScene
                durationInFrames={item.durationInFrames}
                index={item.phraseIndex}
                total={phrases.length}
                tickFile={tickFile}
                tickVolume={config.tickVolume}
              />
            );
          } else if (item.type === "reveal") {
            content = (
              <RevealScene
                phrase={phrases[item.phraseIndex]}
                index={item.phraseIndex}
                total={phrases.length}
                revealSoundFile={revealSoundFile}
                revealSoundVolume={config.revealSoundVolume}
                ttsFile={ttsRevealFiles[item.phraseIndex] ?? null}
                ttsVolume={config.revealVoiceVolume}
              />
            );
          } else {
            content = <OutroScene ctaUrl={config.ctaUrl} />;
          }

          return (
            <Fragment key={i}>
              <TransitionSeries.Sequence durationInFrames={item.durationInFrames}>{content}</TransitionSeries.Sequence>
              {i === lastRevealIndex && (
                <TransitionSeries.Transition presentation={fade()} timing={linearTiming({ durationInFrames: transitionFrames })} />
              )}
            </Fragment>
          );
        })}
      </TransitionSeries>
    </ThemeProvider>
  );
}
